### PR TITLE
fix: cannot stop importing images MAASENG-2864

### PR DESCRIPTION
**Pull request by petermakowski**
## Done

This PR fixes the issue where users cannot stop the importing of images. It also adds the buttonsBehavior prop to FormikForm and FormikFormButtons.

- fix: cannot stop importing images MAASENG-2864
- add buttonsBehavior to FormikForm and FormikFormButtons
- selected for download variant displayed with a correct number of columns

#### buttonsBehavior
The buttonsBehavior prop determines the behavior of the primary and secondary submit buttons:

- "coupled" (default): The secondary submit button is disabled if the primary submit button is disabled.
- "independent": The secondary submit button's disabled state is controlled independently.

## QA steps

- [ ] Go to Images page
- [ ] select and download some images
- [ ] Verify the `Stop import` button is enabled as soon as you press the `Update selection` button

## Fixes

Fixes: MAASENG-2864 https://bugs.launchpad.net/maas/+bug/2057689

## Screenshots
Google Chrome screenshot 001645@2x

Button enabled as soon as request is made

Google Chrome screenshot 001643@2x
Button is disabled when cancellation is in progress

Google Chrome screenshot 001647@2x

correct number of columns

### CODE REVIEW

**Comment by ndv99** [comment]
Something I noticed (which can be fixed seperately), the "Deployable in memory" column should have a `-` for images that are selected for download, to ensure the spacing is correct:

image

**Comment by ndv99** [comment]
Also, clicking the "Stop import" button after downloading some images doesn't show the "Stopping image import" text, it just seems to vanish

**Comment by petermakowski** [comment]
> Also, clicking the "Stop import" button after downloading some images doesn't show the "Stopping image import" text, it just seems to vanish

Which image type was this?

**Comment by ndv99** [comment]
> > Also, clicking the "Stop import" button after downloading some images doesn't show the "Stopping image import" text, it just seems to vanish
> 
> Which image type was this?

Ubuntu. Specifically, 23.10 for amd64

**Review by ndv99 — APPROVED** [review]
LGTM

**Pull request merged**
