### PR TITLE
3.0 branch: select fixes only (for maas 3.0.1)

### PR DESCRIPTION
**Pull request by mfoliveira**
## Done

This PR reverts the non-fix commits (ie, feature/refactor) from the 3.0 branch,
in preparation for MAAS 3.0.1 release, which is in bug-fix only support mode.

Details are provided in the revert commits.

We'll check the GitHub CI tests and address issues. Thanks!

### Git history
These are the new commits since the maas-ui commit used by the submodule
(notice its commit id changed, previously from `main` to the backport in `3.0`):

```
$ git checkout origin/3.0
$ git submodule update --init --recursive --force
Submodule path 'src/maas-offline-docs/src': checked out 'a18ff68fe6c6043a35d5a5620c111daa2c5926c4'
Submodule path 'src/maasui/src': checked out '545f41330490b1bbfe3dca0bf30ba637d883dbc0'

$ cd src/maasui/src/
$ git log --oneline -1
545f41330490 (HEAD) fix(ui): preselect first PXE network when defining composed VM interface (#2663)

$ git log --oneline origin/3.0 | grep 'fix(ui): preselect first PXE network when defining composed VM interface (#2663)'
512f39e6168f fix(ui): preselect first PXE network when defining composed VM interface (#2663) (#2665)

$ git log --oneline 512f39e6168f..origin/3.0
b1e894c45151 (origin/3.0) ci(ci): use the 3.0 snap (#3927)
011cf6138666 fix(ui): select correct fabric/VLAN when adding an alias or VLAN to nic (#3796) (#3845)
55ccb7627b8f fix(single-spa): fix maas in Safari for 3.0 (#3428)
9fc7f9c592a3 ci(ui): create an issue when Cypress fails (#3073)
093e5d2937fc fix(legacy): fix legacy edit DHCP snippets enabled value (Backport #3006) (#3021)
a87d9a0c3dea feat(ui): add UI support for VMFS7 (3.0 backport) (#3004)
5b37b64b5d69 fix(ui): select the VLAN when creating a bond
07b9a22fab7b fix(ui): don't overwrite events when fetching
c96360c20b8d refactor(all): remove all references to general.navigation_options websocket method (#2683)
42f2c980bc79 feat(legacy): display snap upgrade errors (#2668)
f43c72a546e3 feat(ui): replace legacy pod websocket fields with 'resources' equivalents (#2664)
d92e02757eef fix(legacy): QA fixes for subnet boot architectures form (#2706)
51e69bd00916 feat(legacy): allow disabling boot architectures in subnet details (#2677)
c6afc084d0c5 ci(ci): run actions against the 3.0 branch
```

And these are the reverted commits:
```
$ git log --oneline origin/3.0..
3892241809dd Revert "feat(legacy): allow disabling boot architectures in subnet details (#2677)"
e1de65c992d8 Revert "fix(legacy): QA fixes for subnet boot architectures form (#2706)"
e7812724b359 Revert "feat(ui): replace legacy pod websocket fields with 'resources' equivalents (#2664)"
b57d3ab42bc3 Revert "feat(legacy): display snap upgrade errors (#2668)"
728feff42f75 Revert "refactor(all): remove all references to general.navigation_options websocket method (#2683)"
1824a9a5bfc2 Revert "feat(ui): add UI support for VMFS7 (3.0 backport) (#3004)"
```

So, from the original 14 commits (3 CI fixes, 5 bug fixes, 6 features), the 6 commits with features were reverted, effectively resulting in 8 commits (3 CI fixes, 5 bug fixes).

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [A development MAAS](/HACKING.md#development-deployment)

### Running the branch

You can run this branch by:

- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Follow the steps in the PRs/Issues/LP bugs for each non-reverted commit.

## Fixes

Not related to any Fixes.

## Launchpad issue

Not related to any Launchpad maas issues.

## Backports

Not related.

## Screenshots

Not required.

### CODE REVIEW

**Comment by mfoliveira** [comment]
Hi @petermakowski @ndv99 @huwshimi @sparkiegeek,

Apologies for the spam tagging -- I don't know the right/current review team for the 3.0 branch, and found you in reviews for the more recent branches.

Please, could one of you review this PR?

We'll make a MAAS 3.0.1 release, and it requires a more conservative set of changes on the UI (considering the support scope for 3.0 is now bug-fix only, and reducing the potential for regressions in the long run).

Thanks!

**Comment by mfoliveira** [comment]
> @mfoliveira No worries! Sure, we'll look into this today.

@petermakowski Thank you very much!

**Comment by petermakowski** [comment]
QA+1

Note that I was not able to QA all of the fixes in depth as this was done using a local MAAS 3.0 with maas-test-db.

**Review by petermakowski — APPROVED** [review]

**Comment by mfoliveira** [comment]
@petermakowski Thanks for the review! And for the PR to be merged, process-wise, is there anything I have to do or could help with?

**Comment by mfoliveira** [comment]
Thank you @petermakowski, have a nice weekend!

**Pull request merged**
