### PR TITLE
feat: add lazy loading of base routes

### PR DESCRIPTION
**Pull request by petermakowski**
## Done
- feat: add lazy loading of base routes
  - add LONG_TEST_TIMEOUT
  - add tests for useWindowTitle hook

## QA steps

- [ ] Go to login page
- [ ] Login
- [ ] Once you're redirected to post login page (e.g. machines) you might see a Loading indicator briefly
- [ ] Verify that page bundle has been loaded asynchronously once you landed on it

## Fixes

Fixes: 

## Screenshots
Loading indicator displayed as a fallback for lazily loaded route
Warp screenshot 001425@2x

### CODE REVIEW

**Comment by ndv99** [comment]
You might need to add some `vi.waitFor` calls in the Routes test suite.

**Comment by petermakowski** [comment]
> You might need to add some `vi.waitFor` calls in the Routes test suite.

Thanks, will give it a go, I haven't even tried to look at the failing tests yet.

**Comment by petermakowski** [comment]
> > You might need to add some `vi.waitFor` calls in the Routes test suite.
> 
> Thanks, will give it a go, I haven't even tried to look at the failing tests yet.

Yup, it seems to have fixed it, thanks @ndv99

**Comment by ndv99** [comment]
Looks like the two failing Routes tests are `Displays: LXD at: /kvm` and `redirects from Settings base URL to configuration`

IIRC these were the two that were causing errors for me when I initially tried this. Not sure how easy/hard it would be to fix.

**Review by ndv99 — APPROVED** [review]
Wow, I can actually load the UI in chrome in dev mode!

Nice work man, this is an awesome change.

**Pull request merged**
