### PR TITLE
chore: upgrade vanilla v4 MAASENG-2086

### PR DESCRIPTION
**Pull request by petermakowski**
## Done

chore: upgrade vanilla v4
- update Ubuntu font assets
- update `.section-header__title` top padding to maintain correct alignement with machine list controls

https://vanillaframework.io/docs/migration-guide-to-v4#how-to-update

## QA

This will need thorough QA.
Try to visit all pages and look for anything unexpected, like items no longer being positioned correctly.

### After
image

image

### CODE REVIEW

**Comment by ndv99** [comment]
In MachineDetails and ControllerDetails, the CPU arch is not aligned correctly with the card headers:

image

**Review by Jay-Topher — APPROVED** [review]
Everything looks good so far +1

**Comment by petermakowski** [comment]
> [#5087 (comment)](https://github.com/canonical/maas-ui/pull/5087#issuecomment-1657917338) <--- Please address this before merging 🙏

You raised an important point around changes to heading spacing values. This might need some more thought, and more thorough review.

**Comment by petermakowski** [comment]
I asked @dgtlntv to review this before we merge and included a number of screenshots on JIRA: https://warthogs.atlassian.net/browse/MAASENG-2086

**Comment by petermakowski** [comment]
@ndv99 @Jay-Topher  This has been updated and is now ready for another review.

**Review by ndv99 — APPROVED** [review]
I think this is looking good now, +1

**Pull request merged**
