### PR TITLE
refactor: decrease complexity of ActionForm, NetworkTable, MachineForms

### PR DESCRIPTION
**Pull request by petermakowski**
## Done
- refactor: decrease complexity of ActionForm, NetworkTable, MachineForms
  - add eslint-plugin-complexity
  - add complexity lint rule with max of 25
  
  This is related to TICS checks and intends to improve the overall score for maas-ui.

### CODE REVIEW

**Comment by ndv99** [comment]
This looks *really* clean, I like it. What's the rationale for setting the complexity limit to 25? Is this a recommendation from TiCS, or just reflective of our codebase?

**Comment by petermakowski** [comment]
> This looks _really_ clean, I like it. What's the rationale for setting the complexity limit to 25? Is this a recommendation from TiCS, or just reflective of our codebase?

Very good question, Nick. This is the lowest setting that works in our codebase without refactoring large number of files. I think we should aim at complexity level of 10. I'll add a JIRA issue to our technical debt objective for this.

**Comment by petermakowski** [comment]
@ndv99 https://warthogs.atlassian.net/browse/MAASENG-3342

**Review by ndv99 — APPROVED** [review]
LGTM!

**Pull request merged**
